on:
  push:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocaml_version: [5.4.1]
        deps_install: ["from_opam", "from_master"]
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set
        run: |
          files=$(find packages -type f -name "opam" -exec dirname {} \;)
          json=$(printf '%s' "$files" | jq -R . | jq -s '{include: map({lib: ., ocaml_version: "${{matrix.ocaml_version}}"})}')
          {
            echo "matrix<<EOF"
            echo "$json"
            echo "EOF"
          } >> $GITHUB_OUTPUT

  install-library:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies from master
        if: ${{ matrix.deps_install == 'from_master' }}
        run: |
          git clone https://github.com/Deducteam/lambdapi.git
          opam pin add -n -k path lambdapi .
          opam install --deps-only -d -t lambdapi
          eval $(opam env)
          opam install -y lambdapi
          opam repository -a --set-default add lambdapi https://github.com/deducteam/opam-lambdapi-repository.git
      - name: install dependencies from opam
        if: ${{ matrix.deps_install != 'from_master' }}
        run: |
          opam repository -a --set-default add lambdapi https://github.com/deducteam/opam-lambdapi-repository.git

      - name: setting up opam
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml_version }}
      - name: install library ${{ matrix.lib }} 
        run: |
          echo "installing ${{ matrix.lib }}"
          opam install -y --deps-only "${{ matrix.lib }}"