on:
  push:
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Generate matrix file
        run: |
          mkdir path1
          mkdir path2
          touch path1/opam
          touch path2/opam

          files=$(find . -type f -name "opam" -exec dirname {} \;)
          json=$(printf '%s\n' "$files" | jq -R . | jq -s '{include: map({lib: .})}')

          echo "$json" > matrix.json

      - name: Upload matrix artifact
        uses: actions/upload-artifact@v4
        with:
          name: matrix
          path: matrix.json

  use-matrix:
    runs-on: ubuntu-latest
    needs: generate-matrix

    steps:
      - name: Download matrix artifact
        uses: actions/download-artifact@v4
        with:
          name: matrix

      - id: read
        name: Read matrix file
        run: |
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

      - name: Debug
        run: echo "Lib = ${{ matrix.lib }}"

  # install-library:
  #   needs: generate-matrix
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
  #   steps:
  #     - name: install library ${{ matrix.lib }} 
  #       run: |
  #         echo "installing ${{ matrix.lib }}"